/**
 * Pricing & plan catalog — vendored for standalone frontend builds (CI/AWS).
 * Keep in sync with AVG_Token_Distrubution_Backend/src/lib/plans.ts
 */

export type ProductLine = "TOKEN_HOLDER" | "DEX_AUTOMATION";

export const TOKEN_HOLDER_PLANS = [
  {
    key: "STARTER",
    name: "Starter Pack",
    emoji: "🟢",
    holderCount: 1000,
    priceUSD: 60,
    priceINR: 5000,
    transferType: "Fixed token amount to all wallets",
    completionTime: "Within 24 hours",
    walletLimit: 1000,
    footerLines: ["Transfer Style: Fixed Amount", "Delivery: Within 24 Hours"],
    features: [
      "1,000 wallet creation support",
      "Fixed token amount transferred to all wallets",
      "Full token transfer completed within 24 hours",
      "Excel report with wallet address and transaction status",
      "Blockchain transaction proof",
      "Suitable for BEP20 / ERC20 token distribution",
    ],
    bestFor: "New token launch, basic holder creation, and initial wallet distribution",
    color: "#22c55e",
  },
  {
    key: "GROWTH",
    name: "Growth Pack",
    emoji: "🔵",
    holderCount: 2500,
    priceUSD: 120,
    priceINR: 10000,
    transferType: "Fixed token amount to all wallets",
    completionTime: "Within 24 hours",
    walletLimit: 2500,
    footerLines: ["Transfer Style: Fixed Amount", "Delivery: Within 24 Hours"],
    features: [
      "2,500 wallet creation support",
      "Fixed token amount transferred to all wallets",
      "Full token transfer completed within 24 hours",
      "Excel report with wallet address and transaction status",
      "Blockchain transaction proof",
      "Suitable for community reward and airdrop-style distribution",
    ],
    bestFor: "Early-stage token projects, community growth, and holder expansion",
    color: "#3b82f6",
  },
  {
    key: "SCALE",
    name: "Scale Pack",
    emoji: "🟣",
    holderCount: 5000,
    priceUSD: 210,
    priceINR: 17500,
    transferType: "Custom token amount per wallet",
    completionTime: "Daily batch transfer available",
    walletLimit: 5000,
    dailyBatch: "1,000 to 2,500 wallets per day",
    footerLines: [
      "Transfer Style: Custom / Random Amount",
      "Delivery: Daily Batch Available",
      "Daily Transfer: 1,000 to 2,500 wallets per day",
    ],
    popular: true,
    features: [
      "5,000 wallet creation support",
      "Daily wallet transfer option available",
      "Token amount can be customized per wallet",
      "Example: 100-500 tokens per wallet",
      "Excel report with wallet address, token amount, and transaction hash",
      "Blockchain transaction proof",
      "Batch-wise execution support",
    ],
    bestFor: "Controlled distribution, campaign-based allocation, and structured holder growth",
    color: "#a855f7",
  },
  {
    key: "PRO",
    name: "Pro Pack",
    emoji: "🟠",
    holderCount: 10000,
    priceUSD: 360,
    priceINR: 30000,
    transferType: "Custom/random token amount per wallet",
    completionTime: "Daily batch transfer available",
    walletLimit: 10000,
    dailyBatch: "2,500 to 5,000 wallets per day",
    footerLines: [
      "Transfer Style: Custom / Random Amount",
      "Delivery: Daily Batch Available",
      "Daily Transfer: 2,500 to 5,000 wallets per day",
    ],
    features: [
      "10,000 wallet creation support",
      "Daily batch transfer option available",
      "Custom or random token amount per wallet",
      "Example: 100-500 tokens per wallet",
      "Excel report with wallet address, token amount, and transaction hash",
      "Blockchain transaction proof",
      "Batch gas planning support",
      "Resume safe transfer execution",
    ],
    bestFor: "Active token campaigns, community reward distribution, and larger holder allocation programs",
    color: "#f97316",
  },
  {
    key: "ELITE",
    name: "Elite Pack",
    emoji: "💎",
    holderCount: 25000,
    priceUSD: 720,
    priceINR: 60000,
    transferType: "Custom/random token amount per wallet",
    completionTime: "Custom transfer schedule available",
    walletLimit: 25000,
    dailyBatch: "5,000 to 10,000 wallets per day",
    footerLines: [
      "Transfer Style: Custom / Random Amount",
      "Delivery: Daily Batch Available",
      "Daily Transfer: 5,000 to 10,000 wallets per day",
    ],
    features: [
      "25,000 wallet creation support",
      "Large-scale daily batch transfer option available",
      "Custom or random token amount per wallet",
      "Example: 100-1,000 tokens per wallet",
      "Excel report with wallet address, token amount, and transaction hash",
      "Blockchain transaction proof",
      "Custom transfer schedule available",
      "Advanced batch planning and reporting",
    ],
    bestFor: "Large-scale token distribution, reward campaigns, and high-volume Web3 holder allocation",
    color: "#eab308",
  },
] as const;

export const DEX_AUTOMATION_PLANS = [
  {
    key: "LAUNCH",
    name: "Launch Pack",
    emoji: "🟢",
    oldPriceUSD: 499,
    priceUSD: 199,
    priceINR: 16500,
    billingCycle: "month",
    wallets: 1,
    bots: 2,
    minFrequency: "60 seconds",
    maxTxPerDay: 5000,
    walletLimit: 1,
    features: [
      "1 Token Support",
      "1 Wallet",
      "2 Trading Bots",
      "Minimum Activity Frequency: 60 Seconds",
      "Up to 5,000 Transactions / Day",
      "DEX Liquidity & Market Activity Tools",
    ],
    bestFor: "New token projects",
    color: "#22c55e",
  },
  {
    key: "GROWTH",
    name: "Growth Pack",
    emoji: "🔵",
    oldPriceUSD: 799,
    priceUSD: 449,
    priceINR: 37500,
    billingCycle: "month",
    wallets: 2,
    bots: 5,
    minFrequency: "30 seconds",
    maxTxPerDay: 10000,
    walletLimit: 2,
    features: [
      "1 Token Support",
      "2 Wallets",
      "5 Trading Bots",
      "Minimum Activity Frequency: 30 Seconds",
      "Up to 10,000 Transactions / Day",
      "Advanced DEX Market Activity Management",
    ],
    bestFor: "Growing communities and early-stage traction",
    color: "#3b82f6",
  },
  {
    key: "SCALE",
    name: "Scale Pack",
    emoji: "🟣",
    oldPriceUSD: 1199,
    priceUSD: 649,
    priceINR: 54000,
    billingCycle: "month",
    wallets: 50,
    bots: 50,
    minFrequency: "30 seconds",
    maxTxPerDay: 20000,
    walletLimit: 50,
    features: [
      "1 Token Support",
      "50 Wallets",
      "50 Trading Bots",
      "Minimum Activity Frequency: 30 Seconds",
      "Up to 20,000 Transactions / Day",
      "Professional Liquidity & Trading Automation Tools",
    ],
    bestFor: "Active token projects requiring stronger DEX presence",
    color: "#a855f7",
    popular: true,
  },
  {
    key: "INFINITY",
    name: "Infinity Pack",
    emoji: "🔴",
    oldPriceUSD: 2499,
    priceUSD: 1599,
    priceINR: 133000,
    billingCycle: "month",
    wallets: 100,
    bots: 100,
    minFrequency: "15 seconds",
    maxTxPerDay: 50000,
    walletLimit: 100,
    features: [
      "1 Token Support",
      "100 Wallets",
      "100 Trading Bots",
      "Minimum Activity Frequency: 15 Seconds",
      "Up to 50,000 Transactions / Day",
      "High-Performance DEX Automation System",
    ],
    bestFor: "Large-scale token activity and high-performance campaigns",
    color: "#ef4444",
  },
] as const;

export type TokenHolderPlanKey = (typeof TOKEN_HOLDER_PLANS)[number]["key"];
export type DexPlanKey = (typeof DEX_AUTOMATION_PLANS)[number]["key"];

export type PlanCatalogEntry =
  | (typeof TOKEN_HOLDER_PLANS)[number]
  | (typeof DEX_AUTOMATION_PLANS)[number];

export function findPlan(productLine: string, planKey: string): PlanCatalogEntry | null {
  const plans = productLine === "TOKEN_HOLDER" ? TOKEN_HOLDER_PLANS : DEX_AUTOMATION_PLANS;
  const hit = plans.find((p) => p.key === planKey);
  return hit ?? null;
}
